import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import type { GetStaticProps } from "next";
import type { Quiz } from "@prisma/client";
import { motion } from "framer-motion";
import { Check, Moon, PenNib, Sun } from "phosphor-react";
import { useTheme } from "next-themes";
import * as RadioGroup from "@radix-ui/react-radio-group";

import { trpc } from "~/utils/trpc";
import { itemVariants, listVariants } from "~/utils/animation";
import { trpcSSG } from "~/server/trpc-ssg";

import { LevelBar } from "~/components/LevelBar";
import { Modal, ModalTrigger, ModalWrapper, ModalX } from "~/components/Modal";
import { Button } from "~/components/Form/Button";

import hypetiguerLogoImg from "~/assets/logo.svg";
import hypetiguerLogoDarkImg from "~/assets/logodark.svg";

const items = [
  {
    value: 1,
    memoji: "/very-sad.webp",
  },
  {
    value: 2,
    memoji: "/sad.webp",
  },
  {
    value: 3,
    memoji: "/ok.webp",
  },
  {
    value: 4,
    memoji: "/good.webp",
  },
  {
    value: 5,
    memoji: "/love.webp",
  },
];

export default function Home() {
  const [feedback, setFeedback] = useState("");

  const { data: quizzes } = trpc.useQuery(["quiz.getAll"]);

  const { systemTheme, theme, setTheme } = useTheme();

  const currentTheme = theme === "system" ? systemTheme : theme;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex h-screen max-w-2xl flex-col py-24 px-2 text-zinc-600 sm:px-8">
        {currentTheme === "dark" ? (
          <button
            className="absolute top-2 right-2 flex h-10 w-10 items-center justify-center"
            onClick={() => setTheme("light")}
          >
            <Moon size={24} weight="fill" />
          </button>
        ) : (
          <button
            className="absolute top-2 right-2 flex h-10 w-10 items-center justify-center"
            onClick={() => setTheme("dark")}
          >
            <Sun size={24} weight="fill" />
          </button>
        )}

        <motion.div
          initial={{
            opacity: 0,
          }}
          animate={{
            opacity: 1,
          }}
          transition={{
            duration: 2,
            ease: "easeOut",
          }}
          className="px-2 md:px-0"
        >
          <Image
            src={
              currentTheme === "dark"
                ? hypetiguerLogoDarkImg
                : hypetiguerLogoImg
            }
            alt=""
            width={160}
          />

          <h2 className="mt-6 text-xl font-medium dark:text-gray-100">
            Qual teste você quer realizar?
          </h2>

          <p className="mt-1 text-sm text-zinc-400">
            Inicie escolhendo um dos testes da lista abaixo
          </p>
        </motion.div>

        <motion.ul
          variants={listVariants}
          initial="hidden"
          animate="visible"
          className="mt-8 w-full"
        >
          {quizzes?.map((quiz: Quiz) => (
            <motion.li
              key={quiz.id}
              variants={itemVariants}
              className="w-full border-t border-zinc-200 text-gray-400 first:border-none dark:border-zinc-800"
            >
              <Link
                href="/quizzes/[slug]"
                as={`quizzes/${quiz.slug}`}
                className="flex w-full items-center justify-start gap-4 rounded-sm py-4 px-2 transition-all hover:opacity-80 focus:opacity-80 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-100"
              >
                <>
                  <img
                    className="w-full max-w-[48px]"
                    src={quiz.imageUrl}
                    alt="Image course"
                  />

                  <div className="w-full max-w-[296px]">
                    <span className="text-lg font-semibold text-zinc-800 dark:text-gray-100">
                      {quiz.title}
                    </span>
                    <div
                      className="text-sm leading-4 text-zinc-400"
                      dangerouslySetInnerHTML={{ __html: quiz.description }}
                    />
                  </div>

                  <div className="ml-2 md:ml-6">
                    <LevelBar level={quiz.level} />
                  </div>

                  <span className="ml-auto">
                    {quiz.published ? (
                      <span className="w-22 w-18 flex items-center justify-center gap-2 rounded-md bg-emerald-500 px-2 py-1 text-xs font-semibold text-gray-100">
                        <Check weight="bold" />
                        <span className="hidden md:block">Publicado</span>
                      </span>
                    ) : (
                      <span className="w-22 w-18 flex items-center justify-center gap-2 rounded-md bg-red-500 px-2 py-1 text-xs font-semibold text-gray-100">
                        <PenNib weight="fill" />
                        <span className="hidden md:block">Rascunho</span>
                      </span>
                    )}
                  </span>
                </>
              </Link>
            </motion.li>
          ))}
        </motion.ul>

        <Modal>
          <ModalTrigger asChild>
            <Button>Open</Button>
          </ModalTrigger>

          <ModalWrapper maintainDimensions>
            <ModalX />

            <h4 className="mt-4">Dê a sua opinião para nossa melhora</h4>

            <h1 className="my-4 max-w-sm text-2xl font-bold text-gray-800">
              Como está sendo a sua experiência com o Hypertiguer?
            </h1>

            <RadioGroup.Root onValueChange={setFeedback}>
              {items.map((item) => (
                <RadioGroup.Item
                  className="relative"
                  key={item.value}
                  value={String(item.value)}
                >
                  <img
                    src={item.memoji}
                    alt="memoji"
                    className="w-20 opacity-70 brightness-50"
                  />
                  <RadioGroup.Indicator className="absolute top-0 left-0 transition-all ">
                    <motion.img
                      initial={{
                        opacity: 0,
                      }}
                      animate={{
                        opacity: 1,
                      }}
                      transition={{ duration: 0.1, type: "spring" }}
                      src={item.memoji}
                      alt="memoji"
                      className="w-20 drop-shadow-2xl transition-all"
                    />
                  </RadioGroup.Indicator>
                </RadioGroup.Item>
              ))}
            </RadioGroup.Root>

            <span className="mb-5 font-semibold">
              {feedback === "1" && (
                <span className="text-red-500 mb-5 font-semibold">Tá péssima!</span>
              )}
              {feedback === "2" && (
                <span className="text-amber-600 mb-5 font-semibold">Nada legal.</span>
              )}
              {feedback === "3" && (
                <span className="text-amber-400 mb-5 font-semibold">Aceitável.</span>
              )}
              {feedback === "4" && (
                <span className="text-emerald-400">Muito boa!</span>
              )}
              {feedback === "5" && (
                <span className="text-emerald-400 mb-5 font-semibold">Realmente incrível!</span>
              )}
            </span>

            <hr className="mb-4 w-full border-t border-zinc-300" />

            <span>Quanto mais informações, mais conseguimos evoluir</span>

            <textarea className="border-zinc mt-4 min-h-[120px] w-full resize-none rounded-md border border-zinc-200 bg-gray-200 py-1 px-2 text-sm text-gray-900 shadow-sm outline-none placeholder:text-gray-400 focus:border-indigo-600 disabled:cursor-not-allowed disabled:opacity-50" />

            <Button className="mt-6">Enviar feedback</Button>
          </ModalWrapper>
        </Modal>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  await trpcSSG.prefetchQuery("quiz.getAll");

  return {
    props: {
      trpcState: trpcSSG.dehydrate(),
    },
    revalidate: 60 * 60 * 2, // 2 hours
  };
};
